### ISSUE TITLE
vite添加enhanceApp 报错

### ISSUE THREAD

**Issue by GlenHeart** [dewfall123/doc-component#38]
**Describe the bug**
.vitepress/theme/index.js 添加enhanceApp 报错

**To Reproduce**
.vitepress/theme/index.js 创建文件
添加代码如下: 
![image](https://user-images.githubusercontent.com/24836522/136768369-330026a2-93a4-49a2-84c5-686a6e724d6f.png)

**Expected behavior**
期望是正常的，但是页面是报错了，runtime-core.esm-bundler.js:6568 [Vue warn]: Invalid vnode type when creating vnode: undefined. 
  at <VitePressApp>
**System Info**
- vitepress-for-component version: ^0.16.2
- vite version: ^2.4.1
- Node version:
- OS version: macos

**Additional context**

**Comment by break-a-leg-908** [comment]
importMap: {
    ElementPlus: 'https://cdn.jsdelivr.net/npm/element-plus@1.1.0-beta.20/dist/index.full.min.js',
  } 使用这种方式报props类型需要个string
